version: "3"
services:
  honeypot:
    container_name: honeypot
    build:
      context: .
      dockerfile: honeypot/Dockerfile
      args:
        - PORT=${PORT}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/src/app/logs
  log_formatter:
    container_name: log_formatter
    build:
      context: .
      dockerfile: log_formatter/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/src/app/logs
